
---

### **⚙️ 2. AUTOMATIC DEPLOY CONFIG**  
*(`.render.yaml` - Render.com detects this automatically)*
```yaml
services:
  - type: web
    name: bio-it-farmer-alert
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TWILIO_ACCOUNT_SID
        fromSecret: TWILIO_SID
      - key: TWILIO_AUTH_TOKEN
        fromSecret: TWILIO_TOKEN
      - key: TWILIO_PHONE_NUMBER
        fromSecret: TWILIO_PHONE
      - key: DEEPSEEK_API_KEY
        fromSecret: DEEPSEEK_KEY  # Optional - fallback works without it
    plan: free
